---
name: Create DEV Release
# https://dev.to/koddr/github-action-for-release-your-go-projects-as-fast-and-easily-as-possible-20a2
# https://github.com/orgs/community/discussions/25244
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64


jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build-and-push:
    uses: ./.github/workflows/docker-image.yaml
    with:
      push: true
